#!/bin/bash

###################################################
#                                                 #
# Project: Catherine                              #
# File: Catherine_Installer                       #
#                                                 #
# Author(s): {                                    #
#   Hifumi1337 (https://github.com/Hifumi1337)    #
# }                                               #
#                                                 #
###################################################

version="1.1.10"
catherineDir=~/.catherine

function info() {
    echo ""
    echo "[!] Running Installer (+ Updater) v$version"
}

info

function Catherine_Installer() {
    if [ -d "$catherineDir" ];
    then
        echo ""
        echo "[+] Configuring cache..."
        echo ""
        
        sudo rm -r $catherineDir
        mkdir $catherineDir
    else
        mkdir $catherineDir
    fi

    echo ""
    echo "[+] Downloading external modules..."
    echo ""

    git clone https://github.com/cybersuki/catherine-modules
    mv catherine-modules $catherineDir

    echo ""
    echo "[+] Installation complete"
    echo ""
}

Catherine_Installer