#!/bin/bash

# Project: Catherine Framework (https://github.com/jinxsecurity/catherine)
# Author: Jinx Security (https://github.com/jinxsecurity)
# License: BSD 2-Clause

# Created directory for Catherine
catherine_dir="/opt/catherine"

# Installs Catherine
function install_catherine() {
    mkdir $catherine_dir
    cargo install catherine
}

install_catherine

function install_modules() {
    cd $catherine_dir
    git clone https://github.com/jinxsecurity/catherine-modules.git
}

install_modules

function installation_complete() {
    echo "Catherine should now be installed!"
    echo "You can start the framework by simply running `catherine` in your terminal"
}

installation_complete