#!/bin/bash

# Owner: Catherine Framework (https://github.com/CatherineFramework)
# Project: Catherine
# License: BSD 2-Clause

version="1.0.1"
catherineDir=~/.catherine

function info() {
    echo ""
    echo "[!] Running Uninstaller v$version"
}

info

function Catherine_Uninstaller() {
    if [ -d "$catherineDir" ];
    then
        echo ""
        echo "[+] Clearing cache..."
        echo ""
        
        sudo rm -r $catherineDir
    fi

    echo ""
    echo "[+] Successfully uninstalled"
    echo ""
}

Catherine_Installer