#!/bin/bash

###################################################
#                                                 #
# Project: Catherine                              #
# File: Catherine_Uninstaller                     #
#                                                 #
# Author(s): {                                    #
#   Hifumi1337 (https://github.com/Hifumi1337)    #
# }                                               #
#                                                 #
###################################################

version="1.0.1"
catherineDir=~/.catherine

function info() {
    echo ""
    echo "[!] Running Uninstaller v$version"
}

info

function Catherine_Uninstaller() {
    if [ -d "$catherineDir" ];
    then
        echo ""
        echo "[+] Clearing cache..."
        echo ""
        
        sudo rm -r $catherineDir
    fi

    echo ""
    echo "[+] Successfully uninstalled"
    echo ""
}

Catherine_Installer